theme: jekyll-theme-minimal
docs:
  - title: 
    children: "R en INTA"
      - title: "Instalar R y R-Studio"
        url: /r/
      - title: "Material del curso"
        url: /material/
      - title: "Comunidades"
        url: /installation/
      - title: "Congresos regionales"
        url: /congresos/
