theme: jekyll-theme-minimal
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
docs:
  - title: 
    children: "R en INTA"
      - title: "Instalar R y R-Studio"
        url: /docs/r/
      - title: "Material del curso"
        url: /docs/material/
      - title: "Comunidades"
        url: /docs/installation/
      - title: "Congresos regionales"
        url: /docs/congresos/
